import { emptyDir } from "@deno/dnt";

import { parseReleaseVersion } from "./lib/version.ts";
import { ATOMICMAIL_MCP_VERSION } from "./src/mcp/version.ts";

const ROOT = new URL("../", import.meta.url);
const SHARED_SOURCE_DIR = new URL("../shared/", import.meta.url);
const PY_SOURCE_DIR = new URL("../py/src/atomicmail/", import.meta.url);
const PLUGIN_DIR = new URL("../integrations/dify/atomicmail/", import.meta.url);
const VENDOR_DIR = new URL("vendor/", PLUGIN_DIR);
const VENDOR_SHARED_DIR = new URL("shared/", VENDOR_DIR);
const VENDOR_ATOMICMAIL_DIR = new URL("atomicmail/", VENDOR_DIR);
const MANIFEST_PATH = new URL("manifest.yaml", PLUGIN_DIR);
const REQUIREMENTS_PATH = new URL("requirements.txt", PLUGIN_DIR);

const rawVersion = Deno.args[0];
const releaseVersion = rawVersion ? parseReleaseVersion(rawVersion) : null;

async function copyDir(src: URL, dest: URL): Promise<void> {
  await Deno.mkdir(dest, { recursive: true });
  for await (const entry of Deno.readDir(src)) {
    const srcPath = new URL(entry.name, src);
    const destPath = new URL(entry.name, dest);
    if (entry.isDirectory) {
      await copyDir(
        new URL(`${entry.name}/`, src),
        new URL(`${entry.name}/`, dest),
      );
    } else if (entry.isFile) {
      await Deno.copyFile(srcPath, destPath);
    }
  }
}

async function stampManifestVersion(path: URL): Promise<void> {
  const content = await Deno.readTextFile(path);
  const lines = content.split("\n");
  let topLevelStamped = false;
  let metaStamped = false;
  const version = releaseVersion ?? ATOMICMAIL_MCP_VERSION;

  for (let i = 0; i < lines.length; i += 1) {
    if (!topLevelStamped && lines[i].startsWith("version: ")) {
      lines[i] = `version: ${version}`;
      topLevelStamped = true;
      continue;
    }

    if (lines[i] === "meta:") {
      for (let j = i + 1; j < lines.length; j += 1) {
        if (!lines[j].startsWith("  ")) {
          break;
        }
        if (lines[j].startsWith("  version: ")) {
          lines[j] = `  version: ${version}`;
          metaStamped = true;
          break;
        }
      }
    }
  }

  if (!topLevelStamped || !metaStamped) {
    throw new Error(
      "Failed to stamp manifest version fields (expected top-level and meta.version).",
    );
  }

  await Deno.writeTextFile(path, `${lines.join("\n")}\n`);
}

async function writeRequirements(path: URL): Promise<void> {
  const content = [
    "# Generated by ts/build_dify_wrapper.ts",
    "dify_plugin>=0.5.0,<0.7.0",
    "",
  ].join("\n");
  await Deno.writeTextFile(path, content);
}

await emptyDir(new URL("./", VENDOR_DIR).pathname);
await copyDir(SHARED_SOURCE_DIR, VENDOR_SHARED_DIR);
await copyDir(PY_SOURCE_DIR, VENDOR_ATOMICMAIL_DIR);
await writeRequirements(REQUIREMENTS_PATH);
if (releaseVersion) {
  await stampManifestVersion(MANIFEST_PATH);
}

console.log(
  `Built Dify wrapper vendor assets @atomicmail/mcp@${
    releaseVersion ?? ATOMICMAIL_MCP_VERSION
  } -> ./integrations/dify/atomicmail/vendor`,
);
console.log(
  releaseVersion
    ? "Vendored shared assets and Python SDK, updated requirements, and stamped manifest version."
    : "Vendored shared assets and Python SDK, updated requirements.",
);
console.log(`Workspace root: ${ROOT.pathname}`);
