// Zero-deps n8n vendor bundler: esbuild @atomicmail/agentic-core entry into a single
// Cloud-safe ESM file (no node:fs/path/process, no setTimeout/globalThis in output).
// Generates bundled presets and runs `npm run build` prerequisites via core if needed.

import * as esbuild from "npm:esbuild@0.25.0";

import { parseReleaseVersion } from "./lib/version.ts";
import { ATOMICMAIL_MCP_VERSION } from "./src/mcp/version.ts";

const TS_LIB = new URL("./src/lib/", import.meta.url);
const SHARED_PRESETS = new URL("../shared/presets/", import.meta.url);
const PLUGIN_DIR = new URL("../integrations/n8n/atomicmail/", import.meta.url);
const VENDOR_DIR = new URL("vendor/agentic-core/", PLUGIN_DIR);
const VENDOR_INDEX = new URL("index.js", VENDOR_DIR);
const VENDOR_TYPES = new URL("index.d.ts", VENDOR_DIR);
const PRESETS_GENERATED = new URL(
  "integrations/n8n-cloud/bundled-presets.generated.ts",
  TS_LIB,
);
const VENDOR_ENTRY = new URL("integrations/n8n-vendor-entry.ts", TS_LIB);
const SHIM_CREDENTIALS = new URL(
  "integrations/n8n-shims/agent-credentials-store.ts",
  TS_LIB,
);
const SHIM_SHARED = new URL(
  "integrations/n8n-shims/shared-assets.ts",
  TS_LIB,
);
const SHIM_POW = new URL(
  "integrations/n8n-shims/agent-pow.ts",
  TS_LIB,
);
const SHIM_NOBLE_CRYPTO = new URL(
  "integrations/n8n-shims/noble-crypto.ts",
  TS_LIB,
);
const N8N_UTILS = new URL("integrations/n8n-cloud/utils.ts", TS_LIB);
const NODE_PACKAGE_PATH = new URL("package.json", PLUGIN_DIR);

const PRESET_FILES = [
  "list_inbox.json",
  "reply.json",
  "send_mail.json",
  "send_mail_attachment.json",
  "send_mail_blob_attachment.json",
] as const;

const rawVersion = Deno.args[0];
const releaseVersion = rawVersion ? parseReleaseVersion(rawVersion) : null;
const version = releaseVersion ?? ATOMICMAIL_MCP_VERSION;

async function writeBundledPresetsGenerated(): Promise<void> {
  const entries: string[] = [];
  for (const name of PRESET_FILES) {
    const text = await Deno.readTextFile(new URL(name, SHARED_PRESETS));
    entries.push(`  ${JSON.stringify(name)}: ${JSON.stringify(text)},`);
  }
  const content = [
    "// Generated by ts/build_n8n_wrapper.ts — do not edit by hand.",
    "",
    "export const BUNDLED_PRESET_JSON: Record<string, string> = {",
    ...entries,
    "};",
    "",
    "export const BUNDLED_OPS_PRESET_NAMES = [",
    ...PRESET_FILES.map((name) => `  ${JSON.stringify(name)},`),
    "] as const;",
    "",
  ].join("\n");
  await Deno.writeTextFile(PRESETS_GENERATED, content);
}

async function stampNodePackageVersion(): Promise<void> {
  try {
    const pkg = JSON.parse(await Deno.readTextFile(NODE_PACKAGE_PATH)) as {
      version?: string;
    };
    pkg.version = version;
    await Deno.writeTextFile(
      NODE_PACKAGE_PATH,
      `${JSON.stringify(pkg, null, 2)}\n`,
    );
  } catch {
    // package.json may not exist during early scaffold
  }
}

function shimPlugin(nobleEsmDir: string): esbuild.Plugin {
  const credentialsShim = SHIM_CREDENTIALS.pathname;
  const sharedShim = SHIM_SHARED.pathname;
  const powShim = SHIM_POW.pathname;
  const nobleCryptoShim = SHIM_NOBLE_CRYPTO.pathname;
  const n8nUtils = N8N_UTILS.pathname;

  return {
    name: "n8n-cloud-shims",
    setup(build) {
      build.onResolve({ filter: /^@noble\/hashes\/crypto$/ }, () => ({
        path: nobleCryptoShim,
      }));
      build.onResolve({ filter: /^@noble\/hashes\// }, (args) => {
        const sub = args.path.slice("@noble/hashes/".length);
        return { path: `${nobleEsmDir}${sub}.js` };
      });
      build.onResolve({ filter: /agent-credentials-store\.ts$/ }, () => ({
        path: credentialsShim,
      }));
      build.onResolve({ filter: /[/\\]agent-pow\.ts$/ }, () => ({
        path: powShim,
      }));
      build.onResolve({ filter: /shared-assets\.ts$/ }, () => ({
        path: sharedShim,
      }));
      build.onResolve({ filter: /[/\\]core[/\\]utils\.ts$/ }, () => ({
        path: n8nUtils,
      }));
      build.onResolve({ filter: /read-npm-package-readme\.ts$/ }, () => ({
        path: sharedShim,
      }));
    },
  };
}

async function writeVendorTypes(): Promise<void> {
  const dts = `// Generated by ts/build_n8n_wrapper.ts — self-contained vendor API types.

export interface IntegrationEnv {
  authUrl?: string;
  apiUrl?: string;
  scryptSalt?: string;
}

export interface CreateAgentSessionInput {
  store: CredentialStore;
  env?: IntegrationEnv;
  apiKey?: string;
  credentialDir?: string;
}

export interface RegisterResult {
  inbox: string;
  accountId: string;
  apiKey?: string;
  idempotent?: boolean;
}

export interface RegisterOptions {
  forced?: boolean;
}

export interface JmapBlobUploadLimits {
  maxSizeBlobSet: number | null;
  maxDataSources?: number;
}

export interface CredentialArtifacts {
  credentials?: StoredCredentials;
  sessionJwt?: string;
  capabilityJwt?: string;
}

export interface StoredCredentials {
  apiKey: string;
  inboxId: string;
  authUrl: string;
  apiUrl: string;
  scryptSalt: string;
  uploadUrl: string;
  downloadUrl: string;
}

export interface CredentialStore {
  load(): Promise<CredentialArtifacts>;
  save(artifacts: CredentialArtifacts): Promise<void>;
  clear(): Promise<void>;
}

export declare class AgentSession {
  readonly apiUrl: string;
  readonly credentialDir: string;
  readonly hasApiKey: boolean;
  readonly currentInboxId?: string;
  readonly currentUploadUrl?: string;
  readonly currentDownloadUrl?: string;
  register(username: string, options?: RegisterOptions): Promise<RegisterResult>;
  getCapabilityToken(): Promise<string>;
  getPrimaryMailAccountId(): Promise<string>;
  getJmapPostUrl(): Promise<string>;
  getBlobUploadLimitsForAccount(
    accountId: string,
  ): Promise<JmapBlobUploadLimits | null>;
  invalidateJmapSessionCache(): void;
  destroy(): void;
}

export declare function createAgentSession(
  input: CreateAgentSessionInput,
): Promise<AgentSession>;

export interface N8nKeyValueBackend {
  get(key: string): Promise<string | undefined> | string | undefined;
  set(key: string, value: string): Promise<void> | void;
  delete(key: string): Promise<void> | void;
  has?(key: string): Promise<boolean> | boolean;
}

export declare function createN8nCredentialStore(
  backend: N8nKeyValueBackend,
  accountId?: string,
): CredentialStore;

export declare const createKeyValueStore: typeof createN8nCredentialStore;

export declare function n8nStaticDataBackend(
  data: Record<string, unknown>,
): N8nKeyValueBackend;

export declare const DEFAULT_JMAP_USING: readonly string[];

export interface IntegrationJmapSessionPort {
  readonly apiUrl: string;
  getJmapPostUrl(): Promise<string>;
  getPrimaryMailAccountId(): Promise<string>;
  getCapabilityToken(): Promise<string>;
  readonly currentInboxId?: string;
  readonly currentUploadUrl?: string;
  readonly currentDownloadUrl?: string;
  getBlobUploadLimitsForAccount(
    accountId: string,
  ): Promise<JmapBlobUploadLimits | null>;
}

export interface RunJmapRequestInput {
  session: IntegrationJmapSessionPort;
  opsJson: string;
  defaultUsing: string[];
  sourceLabel: string;
  dryRun?: boolean;
  vars?: Record<string, string>;
}

export declare function runJmapRequest(
  input: RunJmapRequestInput,
): Promise<{ ok: boolean; status: number; bodyText: string }>;

export declare const BUNDLED_OPS_PRESET_NAMES: readonly string[];

export declare function readOpsFile(
  credentialDir: string,
  opsFile: string,
): Promise<string>;

export declare const HELP_TOPIC_LIST: string[];

export declare function getHelp(
  topic?: string,
  runtime?: "mcp" | "skill",
): Promise<string>;

export declare function sharedError(key: string): string;

export declare const postRegisterCronReminder: string;

export declare function guessMimeTypeFromFilename(name: string): string;

export declare function expandUploadUrl(
  template: string,
  accountId: string,
): string;

export declare function postBinaryBlobUpload(
  uploadUrlExpanded: string,
  capabilityJwt: string,
  bytes: Uint8Array,
  contentType: string,
): Promise<{ blobId: string; size: number }>;

export declare function assertAttachmentBytesWithinBlobLimit(
  attachments: Array<{ label: string; byteLength: number }>,
  limits: JmapBlobUploadLimits | null,
): void;
`;
  await Deno.writeTextFile(VENDOR_TYPES, dts);
}

async function cleanVendorDir(): Promise<void> {
  try {
    for await (const entry of Deno.readDir(VENDOR_DIR)) {
      const path = new URL(entry.name, VENDOR_DIR);
      if (entry.name === "index.js" || entry.name === "index.d.ts") {
        continue;
      }
      await Deno.remove(path, { recursive: true });
    }
  } catch (error) {
    if (!(error instanceof Deno.errors.NotFound)) {
      throw error;
    }
  }
}

await Deno.mkdir(VENDOR_DIR, { recursive: true });
await cleanVendorDir();
await writeBundledPresetsGenerated();

const nobleScryptUrl = import.meta.resolve("npm:@noble/hashes@1.7.1/scrypt");
const nobleScryptPath = new URL(nobleScryptUrl).pathname;
const nobleEsmDir = nobleScryptPath.replace(/\/scrypt\.js$/, "/");

const result = await esbuild.build({
  entryPoints: [VENDOR_ENTRY.pathname],
  outfile: VENDOR_INDEX.pathname,
  bundle: true,
  format: "esm",
  platform: "neutral",
  target: "es2022",
  logLevel: "info",
  plugins: [shimPlugin(nobleEsmDir)],
  legalComments: "none",
});

if (result.errors.length > 0) {
  throw new Error("esbuild n8n vendor bundle failed");
}

await writeVendorTypes();

if (releaseVersion) {
  await stampNodePackageVersion();
}

console.log(
  "Built n8n vendor bundle -> integrations/n8n/atomicmail/vendor/agentic-core/index.js",
);
